name: build

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-python-and-package
        with:
          python-version: ${{ matrix.python-version }}
      - name: Expected failure on Python 3.10
        # failure caused by onnxruntime not supporting 3.10
        if: ${{ failure() && matrix.python-version == 3.10 }}
        run: exit 0
      - name: Run unit tests
        run: pytest -v
      - name: Verify that we can build the package
        run: python3 setup.py sdist bdist_wheel
      - name: Build documentation
        run: make coverage doctest html
        working-directory: docs
